const DURATION_SHORT = 1500;
const DURATION_MEDIUM = 2500;
const DURATION_LONG = 5000;
const DURATION_INFINITY = Number.NEGATIVE_INFINITY;

export {DURATION_SHORT, DURATION_MEDIUM, DURATION_LONG, DURATION_INFINITY};
